<?php
/**
 * @file
 * Code for the D7 Scraping.
 */


/**
 * Implements hook_theme().
 */

function pydream_scraping_theme() {
    return array(
        'pydream_scraping_form_page' => array(
            'variables' => array('items' => NULL),
            'template'  => 'template/pydream_scraping_form_page',
        ),
        'pydream_scraping_listing_page' => array(
            'variables' => array('items' => NULL),
            'template'  => 'template/pydream_scraping_listing_page',
        ),
    );
}

/**
 * Implements hook_permission().
 */
function pydream_scraping_permission() {
    return array(
        'access pydream scraping'  => array(
            'title'         => t('Access pydream scraping'),
            'description'   => t('Access pydream scraping.'),
        ),
        'access pydream scraping save'  => array(
            'title'         => t('Access pydream scraping save'),
            'description'   => t('Access pydream scraping save.'),
        ),
        'access pydream scraping delete'  => array(
            'title'         => t('Access pydream scraping delete'),
            'description'   => t('Access pydream scraping delete.'),
        ),

    );
}

/**
 * Implements hook_menu().
 */
function pydream_scraping_menu() {

    $items = array();

    $items['scraping'] = array(
        'title'             => t('Scraping'),
        'type'              => MENU_NORMAL_ITEM,
        'page callback'     => 'pydream_scraping_page',
        'file'              => 'pydream_scraping_form.inc',
        'access arguments'  => array('access pydream scraping'),
    );

    $items['scraping-save'] = array(
        'title'             => t(''),
        'type'              => MENU_NORMAL_ITEM,
        'page callback'     => '_pydream_scraping_save',
        'file'              => 'pydream_scraping_form.inc',
        'access arguments'  => array('access pydream scraping save'),
    );

    $items['scraping-list'] = array(
        'title'             => t('Scrap List'),
        'type'              => MENU_NORMAL_ITEM,
        'page callback'     => '_pydream_scraping_listing_page',
        'file'              => 'pydream_scraping_form.inc',
        'access arguments'  => array('access pydream scraping'),
    );

    $items['scraping-delete/%'] = array(
        'title'             => t(''),
        'page callback'     => '_scraping_delete',
        'file'              => 'pydream_scraping_admin.inc',
        'access arguments'  => array('access pydream scraping delete'),
        'page arguments' => array(1),
        'type'              => MENU_CALLBACK,
    );
    
    
    
    return $items;
}
